const mods=[['POS / TINDA','🛒','Fast selling & checkout'],['UTANG','📒','Customer credit ledger'],['INVENTORY','📦','Stock & prices'],['PURCHASES','🚚','Supplier stock-in'],['LOW STOCK','⚠️','Reorder warnings'],['EXPENSES','🧾','Store expenses'],['CUSTOMERS','👥','Customers & suppliers'],['REPORTS','📊','Sales & profit']];
const seed={products:[['Coke 1.5L',75,55,4,6],['Lucky Me Pancit Canton',16,12,28,10],['Century Tuna',42,34,7,8],['Bottled Water',15,9,18,12],['SkyFlakes',10,7,5,8]],utang:[['Aling Rosa',320,'Sep 28'],['Mang Ben',180,'Oct 1'],['Jenny',95,'Sep 30']],expenses:[['Electricity',650],['Delivery',120]],sales:4850};
let db=JSON.parse(localStorage.getItem('tindahanDB')||'null')||seed; const save=()=>{localStorage.setItem('tindahanDB',JSON.stringify(db));stats()};
const orbit=document.getElementById('orbit');mods.forEach((m,i)=>{let a=(i/8)*Math.PI*2-Math.PI/2,x=50+39*Math.cos(a),y=50+39*Math.sin(a);orbit.insertAdjacentHTML('beforeend',`<button class="orb" style="left:${x}%;top:${y}%" onclick="openMod(${i})"><i>${m[1]}</i>${m[0]}</button>`)});orbit.insertAdjacentHTML('beforeend','<button class="orb center" style="left:50%;top:50%" onclick="today()"><b>TODAY</b><small>Tap dashboard</small></button>');
function money(n){return '₱'+Number(n).toLocaleString()}function stats(){let cost=db.products.reduce((a,p)=>a+(p[1]-p[2])*Math.min(p[3],5),0),u=db.utang.reduce((a,x)=>a+x[1],0),low=db.products.filter(p=>p[3]<=p[4]).length; sales.textContent=money(db.sales);profit.textContent=money(Math.round(cost));utangTotal.textContent=money(u);lowCount.textContent=low}
function show(title,sub,html){home.classList.add('hidden');panel.classList.remove('hidden');ptitle.textContent=title;psub.textContent=sub;pbody.innerHTML=html}function goHome(){panel.classList.add('hidden');home.classList.remove('hidden');stats()}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1600)}
function today(){let u=db.utang.reduce((a,x)=>a+x[1],0),low=db.products.filter(p=>p[3]<=p[4]).length;show('TODAY','Live store command center',`<div class="cards"><div class="card">Sales<b>${money(db.sales)}</b>today</div><div class="card">Outstanding Utang<b>${money(u)}</b>${db.utang.length} customers</div><div class="card">Needs Attention<b>${low}</b>low-stock items</div></div><div class="box" style="margin-top:12px"><h3>Smart Tindahan Assistant</h3><p>${low?'You have '+low+' products at or below reorder level. Open Low Stock to prepare a restock list.':'Stock levels look healthy.'}</p></div>`)}
function openMod(i){const m=mods[i]; if(i===0)return pos();if(i===1)return utang();if(i===2)return inventory();if(i===3)return purchases();if(i===4)return low();if(i===5)return expenses();if(i===6)return customers();reports()}
function pos(){show('POS / TINDA','Fast checkout',`<div class="actions">${db.products.map((p,i)=>`<button class="secondary" onclick="sell(${i})">${p[0]} · ${money(p[1])}</button>`).join('')}</div><div class="box"><b>Tap a product</b><p>Each tap records one sale and automatically deducts one from inventory.</p></div>`)}function sell(i){let p=db.products[i];if(p[3]<1)return toast('Out of stock');p[3]--;db.sales+=p[1];save();toast(p[0]+' sold · '+money(p[1]));pos()}
function utang(){show('UTANG LEDGER','Customer credit & payments',`<div class="actions"><input id="un" placeholder="Customer"><input id="ua" type="number" placeholder="Amount"><button class="primary" onclick="addUtang()">+ Add Utang</button></div><table><tr><th>Customer</th><th>Balance</th><th>Due</th><th></th></tr>${db.utang.map((u,i)=>`<tr><td>${u[0]}</td><td><b>${money(u[1])}</b></td><td>${u[2]}</td><td><button class="secondary" onclick="pay(${i})">Bayad</button></td></tr>`).join('')}</table>`)}function addUtang(){if(!un.value||!+ua.value)return;db.utang.push([un.value,+ua.value,'Open']);save();utang()}function pay(i){let a=prompt('Payment amount');if(!a)return;db.utang[i][1]=Math.max(0,db.utang[i][1]-Number(a));if(!db.utang[i][1])db.utang.splice(i,1);save();utang()}
function inventory(){show('INVENTORY','Stock, cost & selling price',`<table><tr><th>Product</th><th>Price</th><th>Cost</th><th>Stock</th><th>Status</th></tr>${db.products.map(p=>`<tr><td><b>${p[0]}</b></td><td>${money(p[1])}</td><td>${money(p[2])}</td><td>${p[3]}</td><td class="${p[3]<=p[4]?'warn':'ok'}">${p[3]<=p[4]?'LOW':'OK'}</td></tr>`).join('')}</table>`)}
function purchases(){show('PURCHASES','Supplier deliveries & stock-in',`<div class="box"><h3>Quick Stock-In</h3><div class="actions"><select id="pp">${db.products.map((p,i)=>`<option value="${i}">${p[0]}</option>`).join('')}</select><input id="pq" type="number" value="12" min="1"><button class="primary" onclick="stockin()">Receive Stock</button></div></div>`)}function stockin(){db.products[+pp.value][3]+=+pq.value;save();toast('Stock received');purchases()}
function low(){let x=db.products.filter(p=>p[3]<=p[4]);show('LOW STOCK','Items needing replenishment',`<table><tr><th>Product</th><th>Left</th><th>Reorder at</th><th>Suggested</th></tr>${x.map(p=>`<tr><td><b>${p[0]}</b></td><td class="warn">${p[3]}</td><td>${p[4]}</td><td>${Math.max(12,p[4]*2-p[3])} pcs</td></tr>`).join('')}</table>`)}
function expenses(){show('EXPENSES','Track money going out',`<div class="actions"><input id="en" placeholder="Expense"><input id="ea" type="number" placeholder="Amount"><button class="primary" onclick="addExpense()">+ Add</button></div><table>${db.expenses.map(e=>`<tr><td>${e[0]}</td><td><b>${money(e[1])}</b></td></tr>`).join('')}</table>`)}function addExpense(){if(!en.value||!+ea.value)return;db.expenses.push([en.value,+ea.value]);save();expenses()}
function customers(){show('CUSTOMERS & SUPPLIERS','Relationships in one place',`<div class="cards"><div class="card">Credit Customers<b>${db.utang.length}</b>with open balance</div><div class="card">Suppliers<b>3</b>sample suppliers</div><div class="card">Customer Credit<b>${money(db.utang.reduce((a,u)=>a+u[1],0))}</b>outstanding</div></div>`)}
function reports(){let rev=db.sales,exp=db.expenses.reduce((a,e)=>a+e[1],0);show('REPORTS','Owner-only business snapshot',`<div class="cards"><div class="card">Sales<b>${money(rev)}</b>today</div><div class="card">Expenses<b>${money(exp)}</b>recorded</div><div class="card">Net after expenses<b>${money(rev-exp)}</b>simple cash view</div></div>`)}stats();