const mods=[['POS / TINDA','🛒'],['UTANG','📒'],['INVENTORY','📦'],['PURCHASES','🚚'],['LOW STOCK','⚠️'],['EXPENSES','🧾'],['CUSTOMERS','👥'],['REPORTS','📊']];
const seed={products:[['Coke 1.5L',75,55,4,6],['Lucky Me Pancit Canton',16,12,28,10],['Century Tuna',42,34,7,8],['Bottled Water',15,9,18,12],['SkyFlakes',10,7,5,8]],utang:[['Aling Rosa',320,'Sep 28'],['Mang Ben',180,'Oct 1'],['Jenny',95,'Sep 30']],expenses:[['Electricity',650],['Delivery',120]],sales:4850,transactions:[],role:'OWNER'};
let db=JSON.parse(localStorage.getItem('tindahanDB')||'null')||seed;db.transactions=db.transactions||[];db.role=db.role||'OWNER';let cart=[];
const save=()=>localStorage.setItem('tindahanDB',JSON.stringify(db)),money=n=>'₱'+Number(n||0).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2});
const orbit=document.getElementById('orbit');mods.forEach((m,i)=>{let a=i/8*Math.PI*2-Math.PI/2,x=50+39*Math.cos(a),y=50+39*Math.sin(a);orbit.insertAdjacentHTML('beforeend',`<button class="orb" style="left:${x}%;top:${y}%" onclick="openMod(${i})"><i>${m[1]}</i>${m[0]}</button>`)});orbit.insertAdjacentHTML('beforeend','<button class="orb center" style="left:50%;top:50%" onclick="today()"><b>TODAY</b><small>Tap dashboard</small></button>');
account.textContent=db.role+' ▾';account.onclick=()=>{db.role=db.role==='OWNER'?'STAFF':'OWNER';save();account.textContent=db.role+' ▾';toast('Switched to '+db.role+' demo view')};
function show(t,s,h){home.classList.add('hidden');panel.classList.remove('hidden');ptitle.textContent=t;psub.textContent=s;pbody.innerHTML=h}function goHome(){panel.classList.add('hidden');home.classList.remove('hidden')}function toast(s){let t=document.getElementById('toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1700)}
function today(){let u=db.utang.reduce((a,x)=>a+x[1],0),low=db.products.filter(p=>p[3]<=p[4]).length,tx=db.transactions.length;show('TODAY','Store command center',`<div class="cards"><div class="card">Sales<b>${money(db.sales)}</b>today</div><div class="card">Transactions<b>${tx}</b>completed</div><div class="card">Outstanding Utang<b>${money(u)}</b>${db.utang.length} customers</div></div><div class="box" style="margin-top:12px"><h3>Needs attention</h3><p>${low} item(s) are at or below reorder level.</p></div>`)}
function openMod(i){if(i===0)return pos();if(i===1)return utang();if(i===2)return inventory();if(i===3)return purchases();if(i===4)return low();if(i===5)return expenses();if(i===6)return customers();reports()}
function cartTotal(){return cart.reduce((s,c)=>s+db.products[c.i][1]*c.q,0)}
function pos(){let total=cartTotal();show('POS / TINDA','Build cart → review → payment → receipt',`<div class="posgrid"><div><div class="actions"><input id="search" placeholder="Search product / SKU" oninput="filterProducts(this.value)"></div><div id="products" class="productgrid">${productButtons('')}</div></div><div class="cartbox"><h3>Current Cart <span class="pill">${cart.reduce((s,c)=>s+c.q,0)} items</span></h3><div id="cartlines">${cartHTML()}</div><div class="carttotal"><span>TOTAL</span><b>${money(total)}</b></div><button class="primary wide" ${cart.length?'':'disabled'} onclick="payment()">Proceed to Payment</button><button class="secondary wide" onclick="cart=[];pos()">Clear Cart</button></div></div>`)}
function productButtons(q){q=q.toLowerCase();return db.products.map((p,i)=>({p,i})).filter(x=>x.p[0].toLowerCase().includes(q)).map(x=>`<button class="product" onclick="addCart(${x.i})"><b>${x.p[0]}</b><span>${money(x.p[1])}</span><small>Stock: ${x.p[3]}</small></button>`).join('')||'<p>No product found.</p>'}
function filterProducts(q){products.innerHTML=productButtons(q)}function addCart(i){let p=db.products[i],c=cart.find(x=>x.i===i),qty=c?c.q:0;if(qty>=p[3])return toast('Not enough stock');c?c.q++:cart.push({i,q:1});pos()}
function cartHTML(){if(!cart.length)return '<p class="muted">Cart is empty. Tap a product to add it.</p>';return cart.map((c,n)=>{let p=db.products[c.i];return `<div class="cartline"><div><b>${p[0]}</b><small>${money(p[1])} each</small></div><div class="qty"><button onclick="qty(${n},-1)">−</button><b>${c.q}</b><button onclick="qty(${n},1)">+</button></div><b>${money(p[1]*c.q)}</b></div>`}).join('')}
function qty(n,d){let c=cart[n],p=db.products[c.i];if(d>0&&c.q>=p[3])return toast('Not enough stock');c.q+=d;if(c.q<=0)cart.splice(n,1);pos()}
function payment(){let total=cartTotal();show('PAYMENT','Confirm payment before stock is deducted',`<div class="checkout box"><div class="carttotal"><span>Amount Due</span><b>${money(total)}</b></div><label>Payment Method</label><div class="paymethods"><button class="pay active" onclick="pickPay(this,'Cash')">Cash</button><button class="pay" onclick="pickPay(this,'GCash')">GCash</button><button class="pay" onclick="pickPay(this,'Maya')">Maya</button></div><input type="hidden" id="method" value="Cash"><label>Amount Received</label><input id="received" type="number" inputmode="decimal" value="${total}" oninput="calcChange()"><div class="change">Sukli <b id="change">${money(0)}</b></div><div class="actions"><button class="secondary" onclick="pos()">← Back to Cart</button><button class="primary" onclick="completeSale()">Complete Sale</button></div></div>`)}
function pickPay(el,m){document.querySelectorAll('.pay').forEach(x=>x.classList.remove('active'));el.classList.add('active');method.value=m;if(m!=='Cash'){received.value=cartTotal();received.disabled=true}else received.disabled=false;calcChange()}function calcChange(){change.textContent=money(Math.max(0,(+received.value||0)-cartTotal()))}
function completeSale(){let total=cartTotal(),rec=+received.value||0;if(rec<total)return toast('Payment is short');let items=cart.map(c=>({name:db.products[c.i][0],qty:c.q,price:db.products[c.i][1]}));cart.forEach(c=>db.products[c.i][3]-=c.q);db.sales+=total;let tx={id:'TX-'+Date.now().toString().slice(-6),date:new Date().toLocaleString(),items,total,method:method.value,received:rec,change:rec-total,staff:db.role};db.transactions.unshift(tx);save();cart=[];receipt(tx)}
function receipt(tx){show('SALE COMPLETE','Stock and reports have been updated',`<div class="receipt box"><h2>TINDAHAN SMART</h2><p>${tx.id}<br>${tx.date}</p><hr>${tx.items.map(i=>`<div class="receiptrow"><span>${i.qty}× ${i.name}</span><b>${money(i.qty*i.price)}</b></div>`).join('')}<hr><div class="receiptrow"><b>TOTAL</b><b>${money(tx.total)}</b></div><div class="receiptrow"><span>${tx.method}</span><span>${money(tx.received)}</span></div><div class="receiptrow"><span>Sukli</span><b>${money(tx.change)}</b></div><p>Cashier: ${tx.staff}</p><button class="primary wide" onclick="pos()">New Sale</button><button class="secondary wide" onclick="window.print()">Print Receipt</button></div>`)}
function utang(){show('UTANG LEDGER','Customer credit & payments',`<div class="actions"><input id="un" placeholder="Customer"><input id="ua" type="number" placeholder="Amount"><button class="primary" onclick="addUtang()">+ Add Utang</button></div><table><tr><th>Customer</th><th>Balance</th><th>Due</th><th></th></tr>${db.utang.map((u,i)=>`<tr><td>${u[0]}</td><td><b>${money(u[1])}</b></td><td>${u[2]}</td><td><button class="secondary" onclick="pay(${i})">Bayad</button></td></tr>`).join('')}</table>`)}function addUtang(){if(!un.value||!+ua.value)return;db.utang.push([un.value,+ua.value,'Open']);save();utang()}function pay(i){let a=prompt('Payment amount');if(!a)return;db.utang[i][1]=Math.max(0,db.utang[i][1]-Number(a));if(!db.utang[i][1])db.utang.splice(i,1);save();utang()}
function inventory(){show('INVENTORY','Stock, cost & selling price',`<table><tr><th>Product</th><th>Price</th><th>Cost</th><th>Stock</th><th>Status</th></tr>${db.products.map(p=>`<tr><td><b>${p[0]}</b></td><td>${money(p[1])}</td><td>${money(p[2])}</td><td>${p[3]}</td><td class="${p[3]<=p[4]?'warn':'ok'}">${p[3]<=p[4]?'LOW':'OK'}</td></tr>`).join('')}</table>`)}
function purchases(){show('PURCHASES','Supplier deliveries & stock-in',`<div class="box"><h3>Quick Stock-In</h3><div class="actions"><select id="pp">${db.products.map((p,i)=>`<option value="${i}">${p[0]}</option>`).join('')}</select><input id="pq" type="number" value="12" min="1"><button class="primary" onclick="stockin()">Receive Stock</button></div></div>`)}function stockin(){db.products[+pp.value][3]+=+pq.value;save();toast('Stock received');purchases()}
function low(){let x=db.products.filter(p=>p[3]<=p[4]);show('LOW STOCK','Items needing replenishment',`<table><tr><th>Product</th><th>Left</th><th>Reorder at</th><th>Suggested</th></tr>${x.map(p=>`<tr><td><b>${p[0]}</b></td><td class="warn">${p[3]}</td><td>${p[4]}</td><td>${Math.max(12,p[4]*2-p[3])} pcs</td></tr>`).join('')}</table>`)}
function expenses(){show('EXPENSES','Track money going out',`<div class="actions"><input id="en" placeholder="Expense"><input id="ea" type="number" placeholder="Amount"><button class="primary" onclick="addExpense()">+ Add</button></div><table>${db.expenses.map(e=>`<tr><td>${e[0]}</td><td><b>${money(e[1])}</b></td></tr>`).join('')}</table>`)}function addExpense(){if(!en.value||!+ea.value)return;db.expenses.push([en.value,+ea.value]);save();expenses()}
function customers(){show('CUSTOMERS & SUPPLIERS','Relationships in one place',`<div class="cards"><div class="card">Credit Customers<b>${db.utang.length}</b>with open balance</div><div class="card">Suppliers<b>3</b>sample suppliers</div><div class="card">Customer Credit<b>${money(db.utang.reduce((a,u)=>a+u[1],0))}</b>outstanding</div></div>`)}
function reports(){if(db.role!=='OWNER')return show('REPORTS','Owner access only','<div class="box"><h3>Restricted</h3><p>Switch to OWNER from the top-right account control to view financial reports.</p></div>');let exp=db.expenses.reduce((a,e)=>a+e[1],0);show('REPORTS','Sales and transaction history',`<div class="cards"><div class="card">Sales<b>${money(db.sales)}</b></div><div class="card">Expenses<b>${money(exp)}</b></div><div class="card">Transactions<b>${db.transactions.length}</b></div></div><div class="box" style="margin-top:12px"><h3>Recent Sales</h3>${db.transactions.slice(0,8).map(t=>`<div class="receiptrow"><span>${t.id} · ${t.method}</span><b>${money(t.total)}</b></div>`).join('')||'<p>No new POS transactions yet.</p>'}</div>`)}